### ISSUE TITLE
Implement methods that consume Plist and produce Some(value).

### ISSUE THREAD

**Issue by zummenix** [ebarnard/rust-plist#10]
For example now I have:
```rust
let dict = try_opt!(plist.as_dictionary());
let sn = dict.get("SerialNumber").and_then(Plist::as_string).map(|s| s.to_owned());
```
This is somewhat unfortunate with additional allocation by `to_owned` call.
I would like to have something like this:
```rust
let mut dict = try_opt!(plist.as_dictionary_mut());
let sn = dict.remove("SerialNumber").and_then(Plist::into_string));
```
where `into_string` has signature:
```rust
pub fn into_string(self) -> Option<String>;
```
Maybe there is a better idea.

**Comment by ebarnard** [comment]
There's always:
```rust
let sn = if let Plist::String(s) = dict.remove("SerialNumber") { Some(s) } else { None };
```

But I agree; `into_string` and `into_data` seem like reasonable additions.

**Comment by zummenix** [comment]
@ebarnard, what do you think about `into_array` and `into_dictionary` methods additional to `into_string` and `into_data`? I see that those are also can be helpful.

**Comment by ebarnard** [comment]
Unless you've got a use case I'd rather those them out for now. 

You can already get mutable access to storage and you can't reuse the allocated memory for anything, at least not without `unsafe`.

I'm happy to add them if a concrete need arises.

**Comment by zummenix** [comment]
Actually my use case with `into_dictionary` and `into_array` is the same. But I think we will stick with `into_string` and `into_data` for now.
