### ISSUE TITLE
release 1.4.2/1.5

### ISSUE THREAD

**Issue by cmyr** [ebarnard/rust-plist#103]
I'd love a release so that I can use the same version of quick-xml upstream.

 think 1.4.2 should be fine, although I get confused around how the rules work when you update a dependency to an incompatible version (quick-xml from 0.26 to 0.27).

**Comment by ebarnard** [comment]
A patch release is fine as long as the minimum Rust version doesn't increase. Just released v1.4.2.

**Comment by cmyr** [comment]
Thank you!
