### ISSUE TITLE
How to handle duplicate fields? (from powermetrics)

### ISSUE THREAD

**Issue by graelo** [ebarnard/rust-plist#116]
Hi, thanks for this great crate!

The plist output of `powermetrics` (Apple-provided utility) sometimes contains duplicate fields, for instance

```sh
sudo powermetrics --sample-rate 500 --sample-count 1 --samplers cpu_power,gpu_power,thermal -f plist
```

will contain duplicate `idle_ratio` fields under the gpu node:

```xml
...
    <key>gpu</key>
    <dict>
      <key>freq_hz</key><real>715.009</real>
      <key>idle_ns</key><integer>494798041</integer>
      <key>idle_ratio</key><real>0.940204</real>   <!-- here -->
      <key>dvfm_states</key>
...
      <key>idle_ns</key><integer>494798041</integer>
      <key>idle_ratio</key><real>0.940204</real>   <!-- here -->
      <key>gpu_energy</key><integer>10</integer>
    </dict>
```

Parsing this output with `plist::from_file()` yields a serde `duplicate field` error.

How can such issue be tackled? Is there something you can do in this crate?
Thanks!

**Comment by ebarnard** [comment]
There might be a serde attribute that makes it deserialise multiple fields with the same name into a vec? Otherwise, do you know what do Apple's library does about this?

**Comment by ebarnard** [comment]
This crate might be useful as well, looks like it has serde support and implements a map with multiple values for the same key: https://crates.io/crates/multimap

**Comment by graelo** [comment]
Thanks, that's a brilliant idea. I'll give it a try.

**Comment by ebarnard** [comment]
Any luck?

**Comment by graelo** [comment]
Hello, thanks, I'll try it over the weekend, and let you know.

**Comment by graelo** [comment]
Hi, I was just testing this approach, but it's not clear to me at this point how to make work. I currently have the following struct representing nested elements in the plist

```rust
#[derive(Debug, Deserialize)]
pub(crate) struct Gpu {
    #[serde(rename = "freq_hz")]
    pub(crate) freq_mhz: f64,
    pub(crate) idle_ratio: f64,
    pub(crate) dvfm_states: Vec<DvfmState>,
}
```

Because the fields of the struct are of different types, I can't replace that struct with a `MultiMap<String, f64>`, nor can I declare the field of interest (`idle_ratio` is the duplicated field) as a multimap, the field is a `f64`.

Did you have another approach in mind?

Thanks again, anyway.

**Comment by ebarnard** [comment]
I misunderstood the problem. This is something that is annoyingly not supported by serde.

You could not include `idle_ratio` in the struct - if it is needed you can add
```rust
    #[serde(flatten)]
    extra: HashMap<String, Value>,
```
and then extract from there.

As that's a bit clunky, you could replace `HashMap<String, Value>` with your own struct which implements `Deserialize` just for `idle_ratio`.

Alternatively you could read to a `Value` first and then deserialize using serde. That would remove the duplicate field.

**Comment by graelo** [comment]
Makes sense, indeed, on another project, I happened to do implement `Deserialize`. I'll implement this if I have time.

I think I should close this issue, as it does not have much to do with your crate.

Thanks again @ebarnard and take care.
Cheers
