### ISSUE TITLE
Error reading UTF16 strings from binary plist

### ISSUE THREAD

**Issue by sergeilem** [ebarnard/rust-plist#12]
You have an error in fn read_next in src/binary/reader.rs.
Line 220 must be:
`                let len = 2 * try!(self.read_object_len(n));
`
Instead of:
`                let len = try!(self.read_object_len(n * 2));
`
You must not multiply n on 2 before call read_object_len because read_object_len expects 0x0f as a special value and 0x01..0x0e values as length in 16bit units, not in bytes.

**Comment by ebarnard** [comment]
Good spot. Thanks.
