### ISSUE TITLE
Update dependencies?

### ISSUE THREAD

**Issue by robinst** [ebarnard/rust-plist#15]
I have a project that uses a crate which has plist as a dependency. Because of that, the project currently has 3 different versions of serde in total (0.7.15, 0.8.23 and 0.9.3).

Have you considered updating the dependencies? I can try putting together a pull request if you want. It might also be worth it to wait for Rust 1.15, which will make `serde_codegen` obsolete.

**Comment by ebarnard** [comment]
The `serde-up` branch has been updated for Serde 0.8 (planning on 0.9 soon) but I was waiting for Rust 1.15 to release it (which is on the 2nd I think).

**Comment by ebarnard** [comment]
Version 0.1.0 has been released which uses Serde 0.9.
