### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [ebarnard/rust-plist#18]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by ebarnard** [comment]
Thanks for the heads up.

I'm using rustc-serialize solely for base64 and its Json struct. I'll get rid of it in the next major release.

**Comment by ebarnard** [comment]
Dropped in v0.2.
