### ISSUE TITLE
Serde does not support Option<T>

### ISSUE THREAD

**Issue by mitsuhiko** [ebarnard/rust-plist#19]
I tried to use `foo: Option<String>` in a struct for deserialization but this only produces an InvalidData error. Not wrapping in `Option` makes it works but is obviously not exactly what I want here.

**Comment by ebarnard** [comment]
Is this a plist you have previously serialised using this library or an external one?

If you're trying to deserialise something like below where a key may or may not appear that won't work at the moment. It wasn't possible to implement when I first wrote the Serde impl but it looks like it is now so it's on my todo list.

```rust
struct Thing {
    optional_key: Option<String>
}
```

```xml
<plist>
<dict>
<key>optional_key</key>
<string>Optional Value</string>
</dict>
</plist>
```

**Comment by mitsuhiko** [comment]
It's an Info.plist coming from XCode. The case mentioned is what I am looking for.

**Comment by ebarnard** [comment]
If you're still interested v0.2 should support this use case.

**Comment by mitsuhiko** [comment]
Awesome. Thanks a bunch. Will try asap.

**Comment by ebarnard** [comment]
@mitsuhiko Did you manage to get your use-case to work?

**Comment by mitsuhiko** [comment]
Yes, i think this works now.

**Comment by ebarnard** [comment]
Great. I'll close then.
