### ISSUE TITLE
Update to Serde 1.0

### ISSUE THREAD

**Issue by dtolnay** [ebarnard/rust-plist#21]
Release notes: https://github.com/serde-rs/serde/releases/tag/v1.0.0

**Comment by dtolnay** [comment]
By the way, check out [this approach](https://github.com/serde-rs/serde/blob/v1.0.0/serde/src/lib.rs#L222-L267) for calling your optional Serde dependency "serde" instead of "serde_serialization".

**Comment by ebarnard** [comment]
Updated in v0.2. Thanks.
