### ISSUE TITLE
InvalidData reading binary plist

### ISSUE THREAD

**Issue by jchien14** [ebarnard/rust-plist#22]
Haven't looked in detail, but this failed on both 0.2.1 and 0.1.3, giving Err(InvalidData).
```
$ defaults write /tmp/test.plist Test 1
$ defaults read /tmp/test.plist
{
    Test = 1;
}
>>> open('/tmp/test.plist', 'rb').read()
'bplist00\xd1\x01\x02TTestQ1\x08\x0b\x10\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12'
```

It worked when I converted it to XML, so I'm guessing it's an issue with the binary parser.

**Comment by ebarnard** [comment]
Thanks. Fixed in 0.2.2.

**Comment by jchien14** [comment]
Thanks for the quick fix!

I notice when using 0.2.2, that the above plist isn't handled as I would expect it to. After I call `plist.as_dictionary().get('Test')`, the resulting `Plist` returns `None` when I call `as_integer` (also `as_boolean`) but returns the string `"1"` when I call `as_string`. Should `as_integer` never be called for binary plists?

It appears converting it to XML does also convert it as a string, so I guess this is correct -- just a bit unintuitive given the API options.

**Comment by ebarnard** [comment]
Looking at the defaults man page (https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/defaults.1.html) it seems like it defaults to writing a string unless you specify otherwise.

**Comment by ebarnard** [comment]
as_X could be named better though.
