### ISSUE TITLE
Bump `major` version number

### ISSUE THREAD

**Issue by AdamHarries** [ebarnard/rust-plist#32]
In a recent audit of some of the dependencies of one of my rust projects, I upgraded from version 0.3 to 0.4 of rust-plist, and immediately had to downgrade again, due to a fairly major API change. 

I intend to upgrade as soon as I have the time to rewrite my code to use the new API, but in the meantime I suggest that the version of rust-plist on crates.io has it's major version number bumped (i.e. to 1.0) in order to reflect the API change.

**Comment by zummenix** [comment]
While I'm for 1.0, according to [semver](https://semver.org) version 0.4 is correct:
> 4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by AdamHarries** [comment]
Thanks for the response - I'd missed that part of the semver spec, so I'm happy to close this issue. Out of interest, do you have any timescale for stabilizing the public API? I'm happy to contribute if there is work that needs to be done.

**Comment by zummenix** [comment]
сс @ebarnard

**Comment by ebarnard** [comment]
@AdamHarries I don't have a timescale in mind, but I agree it would be nice to get a 1.0 version out. I think it's quite close. I've opened #33 with a list of everything I can think of that's blocking that release. 

It's mainly menial tasks and a bit of thinking/checking. The only considerable bit of work is improving and future-proofing the `Error` type.

**Comment by ebarnard** [comment]
If you want to help out with anything in #33 please do.
