### ISSUE TITLE
Parsing fails on binary plist containing `uid` typed values

### ISSUE THREAD

**Issue by Bibliofile** [ebarnard/rust-plist#40]
I'll grant this plist is rather unusual, but it does appear to be valid, and passing it through `plutil -convert xml1 out.plist` doesn't error, I haven't tried the XML version as my source provides binary data.

[plists.zip](https://github.com/ebarnard/rust-plist/files/3408481/plists.zip)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$archiver</key>
	<string>NSKeyedArchiver</string>
	<key>$objects</key>
	<array>
		<string>$null</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>4</integer>
			</dict>
			<key>NSRangeCount</key>
			<integer>42</integer>
			<key>NSRangeData</key>
			<dict>
				<key>CF$UID</key>
				<integer>2</integer>
			</dict>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>3</integer>
			</dict>
			<key>NS.data</key>
			<data>
			AwIIAQwGFQEXARkBGwIfCCwBMAEzATUDPAJAAkcBTAFTAVYCWwFk
			Am8CeAJ8AY0BAZABAZsBAaABAqYBAt0BAbwCAYAIA4QIAYYIBZMI
			AZgIA5wIAZ8IAaYIAbAIAbwIAccIAYBAAQ==
			</data>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableData</string>
				<string>NSData</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableData</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableIndexSet</string>
				<string>NSIndexSet</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableIndexSet</string>
		</dict>
	</array>
	<key>$top</key>
	<dict>
		<key>foundItems</key>
		<dict>
			<key>CF$UID</key>
			<integer>1</integer>
		</dict>
	</dict>
	<key>$version</key>
	<integer>100000</integer>
</dict>
</plist>
```

**Comment by ebarnard** [comment]
The binary plist contains `uid` typed values which `plutil` seems to convert into an integer when converting the plist to xml.

These are used exclusively by `NSKeyedArchiver` and are currently not supported as they break feature parity between binary and xml plists. I have no issue with the library supporting `uid`s though if someone (you) has a use case that requires them.

**Comment by Bibliofile** [comment]
Ahh, so that's what it is doing. That makes sense now, I knew something was different about this plist. Thanks!

Support for `uid` values would be very convenient (or at least an error that points out what is going wrong), unfortunately I'm not in control of the source that creates these plists, It would be much nicer to deal with a "normal" plist.

**Comment by ebarnard** [comment]
At some point when I get time I'll implement `uid`s  but in the mean time more informative errors are coming soon (https://github.com/ebarnard/rust-plist/tree/better-errors).

**Comment by ebarnard** [comment]
Do you want to see if #41 fixes your issues.

**Comment by Bibliofile** [comment]
I will give it a shot this weekend, thanks for the quick turnaround!

**Comment by Bibliofile** [comment]
I just switched to using the master branch, and after fixing the build errors caused by changes to the types in `plist::Value` I can confirm that everything appears to be working as intended. Thanks!
