### ISSUE TITLE
Read .pbxproj file 

### ISSUE THREAD

**Issue by fstephany** [ebarnard/rust-plist#42]
I'm trying to read a .pbxproj file. The annoying part of it is that Xcode does not use the XML or binary format for this plist but an older variant (coming from NeXT it seems).

See an [example from NetNewsWire](https://github.com/brentsimmons/NetNewsWire/blob/master/NetNewsWire.xcodeproj/project.pbxproj). And here's [a quite exhaustive overview](http://www.monobjc.net/xcode-project-file-format.html). 

I understand the the appeal to support these files is pretty limited but is it something that you might consider? If not, no worries, I'll go with a custom pest parser ;)

**Comment by ebarnard** [comment]
I'd happily support old style ASCII plists but to be honest I don't think I'll have the time or motivation to implement a parser for them myself.

Also, in case you don't know, if you're on a mac and want a quick solution `plutil -convert xml1 XXXX.pbxproj` will convert the file to an XML plist (note that it will overwrite the original file) which you could read with this library.

**Comment by fstephany** [comment]
> I'd happily support old style ASCII plists but to be honest I don't think I'll have the time or motivation to implement a parser for them myself.

That's alright ;) 

Thanks for the  `plutil` idea. It seems to be there on Ubuntu as well but always return `Unimplemented`.
I'll let you know if I end up writing a custom parser for it.

Thanks!

**Comment by ebarnard** [comment]
Great. I'd be very happy for this create to support ASCII plists.

**Comment by cmyr** [comment]
just to chime in: there's a working string plist parser at https://git.sr.ht/~raph/interp-toy/tree/master/glyphstool/src/plist.rs, if that's useful in any way.

**Comment by fstephany** [comment]
Oh cool, thanks for the pointer @cmyr  I'll check it out over the weekend and see if it's better than my naive implementation.

**Comment by Artoria2e5** [comment]
I recommend renaming the "Ascii" format to OpenStep, to clarify its difference from the derived GnuStep format which has types as expressive as the XML version.

**Comment by ebarnard** [comment]
Released in v1.7.0
