### ISSUE TITLE
Error writing Boolean in binary plist

### ISSUE THREAD

**Issue by BenxiangGe** [ebarnard/rust-plist#51]
For boolean value, "true" should be to writen as **'&[0x09]'**, "false" should be writen **'&[0x08]'**. [Property list](https://en.wikipedia.org/wiki/Property_list#Format). 

| Object type  | Marker byte |
| ------------- | ------------- |
| bool  | 0000 1000 (false) 0000 1001 (true)  |

But in https://github.com/ebarnard/rust-plist/blob/master/src/stream/binary_writer.rs#L456, it is as below,

```
            Value::Boolean(true) => {
                self.writer.write_exact(&[0x08])?;
            }
            Value::Boolean(false) => {
                self.writer.write_exact(&[0x09])?;
            }
```

**Comment by ebarnard** [comment]
Fixed in v0.5.4.
