### ISSUE TITLE
Plist::read and Plist::from_event should can return error, not just ()

### ISSUE THREAD

**Issue by defuz** [ebarnard/rust-plist#6]
I think signature of this methods should be like:

```rust
   pub fn read<R: Read + Seek>(reader: R) -> Result<Plist, PlistError>
   pub fn from_events<T>(events: T) -> Result<Plist, PlistError>
```

Where `PlistError` is re-export of `builder::BuildError ` that is private now.

Without this feature, parsing stream into `Plist` with normal error handling is impossible, since builder mod is private.

**Comment by ebarnard** [comment]
Fixed in 0.0.12
