### ISSUE TITLE
Is there any chance of allowing `plist::Value::from<i128, u128>`, or another API for `i128`, `u128`, common crypto primitives?

### ISSUE THREAD

**Issue by ctrlcctrlv** [ebarnard/rust-plist#76]
```
error[E0277]: the trait bound `plist::Value: From<i128>` is not satisfied
  --> src/arbitrary.rs:67:65
   |
67 | ...r(v)) => { map.insert(key, plist::Value::from(serde_json::from_str::<i128>(&value).unwrap()/* as i64*/)); },
   |                               ^^^^^^^^^^^^^^^^^^ the trait `From<i128>` is not implemented for `plist::Value`
   |
   = help: the following implementations were found:
             <plist::Value as From<&'a bool>>
             <plist::Value as From<&'a f32>>
             <plist::Value as From<&'a f64>>
             <plist::Value as From<&'a i16>>
           and 24 others
```

Despite [this source code comment](https://github.com/groob/plist/blob/master/binary_parser.go#L156) by @groob, not all property list files are used in Apple ecosystem. I'd like this feature.

**Comment by ebarnard** [comment]
‘u128’ isn’t possible as binary plist integers are always signed. ‘i128’ theoretically is.

Is there some software you are trying to interoperate with that uses 128 bit integers in plists? If not you’re probably better off using a byte array.

**Comment by ctrlcctrlv** [comment]
Oh, right, I forgot plist has byte array `Data` element. Thank you :)
