### ISSUE TITLE
Implement 'std::convert::From' for Plist.

### ISSUE THREAD

**Issue by zummenix** [ebarnard/rust-plist#8]
Is it intentional to not implement?

**Comment by ebarnard** [comment]
What is the type you want to convert from?

**Comment by zummenix** [comment]
I was thinking about types that are defined in the `Plist` enum: `Vec<Plist>`, `BTreeMap<String, Plist>`, `bool`, `Vec<u8>`, `DateTime<UTC>`, `f64`,  `i64`, `String`
I'm not sure about other numeric types: `f32`, and all other integers that can be safely converted.
It would be also convenient to implement `From` for slices: `&[Plist]`, `&[u8]`, `&str`. But I think it will be overkill.

**Comment by zummenix** [comment]
Turns out it's not that convenient as I thought. Closing for now.
