### ISSUE TITLE
New major after ddff8e6ab781e1717b000034cee8a43b505534fc?

### ISSUE THREAD

**Issue by jcgruenhage** [ebarnard/rust-plist#89]
ddff8e6ab781e1717b000034cee8a43b505534fc hides `XmlWriter::new` behind a feature, which is a breaking change requiring a new major version. That probably wasn't intentional?

**Comment by ebarnard** [comment]
The whole `stream` module has always been behind `#[cfg(feature = "enable_unstable_features_that_may_break_with_minor_version_bumps")]`. This `cfg`, which I just realised I misspelled, was just to avoid an unused code warning coming from having an uncalled function that isn't accessible from external crates.

**Comment by jcgruenhage** [comment]
Ah, and that misspelling also was the reason that `cargo semver-checks` stumbled over this and reported it as breaking! Thanks for clarifying :)
