### ISSUE TITLE
Support old style plists?

### ISSUE THREAD

**Issue by rsheeter** [ebarnard/rust-plist#93]
I'm was wondering if there would be interest in accepting a PR to add "old style" (https://github.com/opensource-apple/CF/blob/master/CFOldStylePList.c) plist support? 

Context: we use your library to read plists, such as for https://github.com/linebender/norad. Some inputs, notably the files written by https://glyphsapp.com/, are in the old style. It would be nice to be able to use this crate for all our plist needs. https://github.com/simoncozens/rust-font-tools/tree/main/openstep-plist implements and could likely be the basis of a PR.

**Comment by rsheeter** [comment]
...or perhaps it's just a matter of finishing #44? - just realized that's also talking about old style plists.

**Comment by rsheeter** [comment]
Last spam of the day, @anthrotype pointed out https://github.com/raphlinus/interp-toy/blob/main/glyphstool/src/plist.rs could also be a good source for an implementation.

**Comment by ebarnard** [comment]
Yes, I'm very happy to support reading ASCII plists. I think #44 was quite near completion.

**Comment by ebarnard** [comment]
Released in v1.7.0.
