### ISSUE TITLE
RUSTSEC-2022-0048: xml-rs is Unmaintained

### ISSUE THREAD

**Issue by Berrysoft** [ebarnard/rust-plist#94]
https://github.com/netvl/xml-rs/issues/221

I come across to this because of tauri: https://github.com/tauri-apps/tauri/issues/4951

A possible replacement of xml-rs: [quick-xml](https://docs.rs/quick-xml/latest/quick_xml/)

**Comment by ChefKissInc** [comment]
Code in the repository uses quick-xml now. The last crates.io release doesn't

**Comment by Berrysoft** [comment]
Thanks! Looking forward to a new release:)

**Comment by ebarnard** [comment]
v1.4 has now been released.
