### ISSUE TITLE
Default whitespace trimming behavior changed

### ISSUE THREAD

**Issue by magebeans** [ebarnard/rust-plist#97]
The port from xml-rs to quick-xml [changed the default whitespace trimming behavior](https://github.com/ebarnard/rust-plist/commit/147a4f6adf902e222a47c6ec7b16a5ca661fb802#diff-0e5c5e9fb913cfe46dc97c248e4b5df6121bfbc5f020988b27b18facfe256e4aL30) from *not trimming whitespace* to *always trimming whitespace*. Is this intentional? Would it make sense to allow this to be configurable, if intentional?

**Comment by ebarnard** [comment]
It’s not intentional. Definitely a bug.
